version: 2
updates:
  # NPM dependencies
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:00'
    open-pull-requests-limit: 5
    labels:
      - 'dependencies'
      - 'automated'
    reviewers:
      - 'zjgordon'
    assignees:
      - 'zjgordon'
    commit-message:
      prefix: 'chore(deps)'
      include: 'scope'
    # Security updates
    ignore:
      - dependency-name: '*'
        update-types: ['version-update:semver-major']
        # Major updates will be handled manually with major-update label
    # Allow security updates immediately
    allow:
      - dependency-type: 'direct'
      - dependency-type: 'indirect'

  # Docker dependencies
  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:00'
    open-pull-requests-limit: 3
    labels:
      - 'dependencies'
      - 'docker'
      - 'automated'
    reviewers:
      - 'zjgordon'
    assignees:
      - 'zjgordon'
    commit-message:
      prefix: 'chore(docker)'
      include: 'scope'

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '05:00'
    open-pull-requests-limit: 3
    labels:
      - 'dependencies'
      - 'github-actions'
      - 'automated'
    reviewers:
      - 'zjgordon'
    assignees:
      - 'zjgordon'
    commit-message:
      prefix: 'chore(ci)'
      include: 'scope'
