id: CARD-018
title: Env samples & secrets hygiene (baseline configuration)
epic: Epic 1 – Foundations & MVP
sprint: 2025-09-sprint-01
status: todo # todo | doing | review | done | blocked
owner: cursor
links:
  - /docs/ROADMAP.md
  - /docs/TECH_CHOICES.md
  - /docs/SPRINT_WORKFLOW.md
acceptance:
  - '.env.example created at repo root with required environment variables for all core services (API, DB, Redis, Coturn, MinIO, etc.)'
  - Each variable has placeholder or safe default (no secrets committed)
  - 'README.md updated with section Configuration referencing .env.example and how to create .env from it'
  - CONTRIBUTING.md updated with notes on:
      - 'Never committing .env or secrets'
      - 'How to add new env vars safely (update .env.example, docs)'
  - 'Verify .gitignore ensures .env and other secret files are excluded'
  - 'CI updated to fail if .env accidentally committed'
  - 'Add a pre-commit check (optional) to warn on .env changes staged'
  - Update /docs/CURRENT_SPRINT.md with a 5–8 line summary
  - Update /docs/PROJECT_STATUS.md with a one-liner entry under this sprint
  - Update /meta/TASK_STATE.yaml breadcrumb/active status
  - Single Conventional Commit created including [CARD-018]
artifacts:
  created:
    - .env.example
  modified:
    - .gitignore
    - README.md
    - CONTRIBUTING.md
    - .github/workflows/ci.yml (optional: add check for accidental .env)
    - docs/CURRENT_SPRINT.md
    - docs/PROJECT_STATUS.md
    - meta/TASK_STATE.yaml
notes: |
  Scope:
    - Example `.env.example` entries:
        # Database
        POSTGRES_USER=campfyre
        POSTGRES_PASSWORD=changeme
        POSTGRES_DB=campfyre_dev
        # Redis
        REDIS_URL=redis://localhost:6379
        # Coturn
        TURN_USER=campfyre
        TURN_PASSWORD=changeme
        # MinIO
        MINIO_ACCESS_KEY=campfyre
        MINIO_SECRET_KEY=changeme
        # API/Web
        NODE_ENV=development
        PORT=3000
    - README.md “Configuration” section should explain:
        - Copy `.env.example` to `.env` and fill values
        - Used by docker-compose and app runtime
    - CONTRIBUTING.md should add:
        - Always update `.env.example` when adding/removing env vars
        - Never commit `.env` files
    - DoD:
        - `.env.example` present and accurate
        - `.gitignore` ensures no accidental secret commits
        - Contributors can spin up stack with `.env` created from sample
