name: CI

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for accidentally committed .env files
        run: |
          if find . -name ".env" -not -name ".env.example" -type f | grep -q .; then
            echo "❌ Error: .env files found in repository!"
            echo "Please remove .env files and ensure they are in .gitignore"
            find . -name ".env" -not -name ".env.example" -type f
            exit 1
          else
            echo "✅ No .env files found in repository"
          fi

      - name: Check for common secret patterns
        run: |
          # Check for common secret patterns in committed files
          if grep -r -i "password.*=" --include="*.js" --include="*.ts" --include="*.json" --include="*.yml" --include="*.yaml" . | grep -v ".env.example" | grep -v "changeme" | grep -v "your-" | grep -v "example" | grep -q .; then
            echo "⚠️  Warning: Potential secrets found in committed files"
            echo "Please review the following matches:"
            grep -r -i "password.*=" --include="*.js" --include="*.ts" --include="*.json" --include="*.yml" --include="*.yaml" . | grep -v ".env.example" | grep -v "changeme" | grep -v "your-" | grep -v "example"
            echo "If these are legitimate secrets, please move them to environment variables"
          else
            echo "✅ No obvious secrets found in committed files"
          fi

  lint:
    runs-on: ubuntu-latest
    needs: [security]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run linting
        run: npm run lint

  typecheck:
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run type checking
        run: npm run typecheck

  test:
    runs-on: ubuntu-latest
    needs: [typecheck]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test -- --ci

      - name: Upload test artifacts on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: |
            **/junit*.xml
            **/coverage/**

  build:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build packages
        run: npm run build
