version: '3.8'

services:
  # Production build with Nginx
  web-prod:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
      args:
        VITE_API_URL: ${VITE_API_URL:-http://localhost:8000}
        VITE_APP_NAME: ${VITE_APP_NAME:-Campfyre}
        VITE_BASE_PATH: ${VITE_BASE_PATH:-/}
        VITE_ENABLE_ANALYTICS: ${VITE_ENABLE_ANALYTICS:-false}
        VITE_ENABLE_DEBUG_TOOLS: ${VITE_ENABLE_DEBUG_TOOLS:-false}
    ports:
      - '8080:8080'
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped
    networks:
      - campfyre-network

  # Development server
  web-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - VITE_API_URL=${VITE_API_URL:-http://localhost:8000}
      - VITE_APP_NAME=${VITE_APP_NAME:-Campfyre}
      - VITE_DEV_PORT=3000
    volumes:
      - .:/app
      - /app/node_modules
      - /app/dist
    command: ['pnpm', 'run', 'dev', '--host', '0.0.0.0']
    restart: unless-stopped
    networks:
      - campfyre-network

  # Nginx for local development (alternative to web-dev)
  nginx-dev:
    image: nginx:alpine
    ports:
      - '8081:80'
    volumes:
      - ./dist:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web-prod
    networks:
      - campfyre-network

networks:
  campfyre-network:
    driver: bridge

volumes:
  node_modules:
  dist:
